<a href="https://colab.research.google.com/github/Carolalmeida96/ProjetoBAH/blob/main/Aula_2_Atividades.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Ask the user for the first and last numbers of the array
primeiro_ano = int(input("Primeiro número do Array: "))
ultimo_ano = int(input("Último número do Array: "))

# Create the array directly using np.arange
array_anos = np.arange(primeiro_ano, ultimo_ano + 1, dtype=np.int32)

# Print the array and its dtype
print(array_anos)
print(array_anos.dtype)

# Reshape the array into a 2x4 matrix
array_anos = array_anos.reshape(2, 4)

# Print the array and its dtype
print(array_anos)

Primeiro número do Array: 2017
Último número do Array: 2024
[2017 2018 2019 2020 2021 2022 2023 2024]
int32
[[2017 2018 2019 2020]
 [2021 2022 2023 2024]]


In [ ]:
import numpy as np

# Generate a random array
np.random.seed(42)  # For reproducibility
random_array = np.random.randint(0, 10, size=20)  # Random array of 20 integers between 0 and 100
print("Random array:", random_array)

# Define the threshold
threshold = 4

# Find the indices and values that exceed the threshold
indices_exceeding_threshold = np.where(random_array > threshold)
values_exceeding_threshold = random_array[indices_exceeding_threshold]

# Print the results
print("Indices exceeding threshold:", indices_exceeding_threshold)
print("Values exceeding threshold:", values_exceeding_threshold)

# Replace values exceeding the threshold with 0
random_array[indices_exceeding_threshold] = 0

# Print the modified array
print("Modified array:", random_array)

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

# Listas de vendas mensais para as três empresas
vendas_empresa_1 = [50000, 60000, 55000, 58000, 62000, 65000, 70000, 72000, 69000, 75000, 78000, 80000]
vendas_empresa_2 = [45000, 48000, 49000, 52000, 55000, 58000, 60000, 62000, 65000, 68000, 70000, 75000]
vendas_empresa_3 = [40000, 42000, 43000, 46000, 48000, 50000, 52000, 54000, 56000, 58000, 60000, 62000]

# Transformar as listas em arrays numpy
vendas_empresa_1_array = np.array(vendas_empresa_1)
vendas_empresa_2_array = np.array(vendas_empresa_2)
vendas_empresa_3_array = np.array(vendas_empresa_3)

# Lista com os arrays de vendas mensais de cada empresa
vendas_mensais_array = [vendas_empresa_1_array, vendas_empresa_2_array, vendas_empresa_3_array]
print (venda_mensais_array)
# Calcular os valores mínimo, máximo e médio para cada empresa (lista e array)
for i, vendas_empresa in enumerate(vendas_mensais_array, start=1):
    print(f"Empresa {i}:")
    print(f"  Lista - Mínimo: {min(vendas_empresa)}, Máximo: {max(vendas_empresa)}, Médio: {sum(vendas_empresa) / len(vendas_empresa)}")
    print(f"  Array - Mínimo: {np.min(vendas_empresa)}, Máximo: {np.max(vendas_empresa)}, Médio: {np.mean(vendas_empresa)}")



In [ ]:
# Criar uma matriz de vendas mensais com os arrays de vendas de cada empresa
matriz_vendas_mensais = np.array([vendas_empresa_1_array, vendas_empresa_2_array, vendas_empresa_3_array])


# Calcular a média das vendas de cada empresa
media_por_mes = np.mean(matriz_vendas_mensais, axis=1)
print(media_por_mes)
# Adicionar uma coluna com os resultados de soma por mês
matriz_vendas_mensais_com_media_mes = np.column_stack((matriz_vendas_mensais, media_por_mes))

# Imprimir a matriz com a coluna de soma por mês
print("Matriz de vendas mensais com soma por mês:")
print(matriz_vendas_mensais_com_media_mes)

In [ ]:
# Calcular a média de cada coluna
media_por_coluna = np.mean(matriz_vendas_mensais_com_media_mes, axis=0)
print (media_por_coluna)
# Adicionar uma nova linha com as médias de vendas por mês
matriz_vendas_mensais_com_media_mes_e_media_coluna = np.vstack((matriz_vendas_mensais_com_media_mes, media_por_coluna))

# Imprimir a matriz com a nova linha de média por coluna
print("Matriz de vendas mensais com média por coluna:")
print(matriz_vendas_mensais_com_media_mes_e_media_coluna)

In [ ]:
nova_matriz = np.delete(matriz_vendas_mensais_com_media_mes_e_media_coluna, 3, axis=0)

print(nova_matriz)

nova_matriz = np.delete(nova_matriz, 12, axis=1)

trimestre1 = matriz_vendas_mensais[:, :3]
trimestre2 = matriz_vendas_mensais[:, 3:6]
trimestre3 = matriz_vendas_mensais[:, 6:9]
trimestre4 = matriz_vendas_mensais[:, 9:]

print(nova_matriz)
print("Trimestre 1:")
print(trimestre1)
print()

print("Trimestre 2:")
print(trimestre2)
print()

print("Trimestre 3:")
print(trimestre3)
print()

print("Trimestre 4:")
print(trimestre4)

In [ ]:
# Fatores de crescimento ou queda para cada trimestre
fator_trimestre1 = 1.05  # crescimento de 5%
fator_trimestre2 = 1.15  # crescimento de 15%
fator_trimestre3 = 0.95  # queda de 5%
fator_trimestre4 = 1.20  # crescimento de 20%

# Calculando as vendas esperadas para o próximo ano
vendas_esperadas_trimestre1 = trimestre1 * fator_trimestre1
vendas_esperadas_trimestre2 = trimestre2 * fator_trimestre2
vendas_esperadas_trimestre3 = trimestre3 * fator_trimestre3
vendas_esperadas_trimestre4 = trimestre4 * fator_trimestre4

# Imprimindo as vendas esperadas para cada trimestre
print("Vendas esperadas para o próximo ano:")
print("Trimestre 1:")
print(vendas_esperadas_trimestre1)
print()
print("Trimestre 2:")
print(vendas_esperadas_trimestre2)
print()
print("Trimestre 3:")
print(vendas_esperadas_trimestre3)
print()
print("Trimestre 4:")
print(vendas_esperadas_trimestre4)

In [ ]:
# Agrupar os arrays em uma matriz mantendo sua configuração original
matriz_vendas_esperadas = np.array((vendas_esperadas_trimestre1,
                                          vendas_esperadas_trimestre2,
                                          vendas_esperadas_trimestre3,
                                          vendas_esperadas_trimestre4))

# Imprimir a matriz resultante
print("Matriz de vendas esperadas para o próximo ano por semestre:\n")
print(matriz_vendas_esperadas)
print()

matriz_esperadas = np.concatenate((vendas_esperadas_trimestre1,
                                          vendas_esperadas_trimestre2,
                                          vendas_esperadas_trimestre3,
                                          vendas_esperadas_trimestre4), axis=1)

# Imprimir a matriz resultante
print("Matriz de vendas esperadas para o próximo ano por empresa:\n")
print(matriz_esperadas)