<a href="https://colab.research.google.com/github/Carolalmeida96/ProjetoBAH/blob/main/Aula_2_Atividades.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Atividade 1

Crie um Array que vá do número 2017 até 2024. Comente qual a principal diferença de um array para uma lista? Printe o tipo do array e o tipo dos elementos do array. Transforme esse array num array bidimensional.

Desafio: Mude o tipo dos elementos array para o que ocupe menos memória possível sem alterar os elementos do array.



In [ ]:
import numpy as np

# Ask the user for the first and last numbers of the array
primeiro_ano = int(input("Primeiro número do Array: "))
ultimo_ano = int(input("Último número do Array: "))

# Create the array directly using np.arange
array_anos = np.arange(primeiro_ano, ultimo_ano + 1, dtype=np.int32)

# Print the array and its dtype
print(array_anos)
print(array_anos.dtype)

# Reshape the array into a 2x4 matrix
array_anos = array_anos.reshape(2, 4)

# Print the array and its dtype
print(array_anos)

Atividade 2
Crie um array de números aleatórios entre 0 e 10;
Defina um valor limite de 0 a 10, por exemplo, 4;
Encontre os índices dos elementos maiores do que o valor limite;
Acessar os valores dos elementos maiores do que o valor limite;
Substitua os valores maiores que o limite por 0.

In [ ]:
import numpy as np

# Generate a random array
np.random.seed(42)  # For reproducibility
random_array = np.random.randint(0, 10, size=20)  # Random array of 20 integers between 0 and 100
print("Random array:", random_array)

# Define the threshold
threshold = 4

# Find the indices and values that exceed the threshold
indices_exceeding_threshold = np.where(random_array > threshold)
values_exceeding_threshold = random_array[indices_exceeding_threshold]

# Print the results
print("Indices exceeding threshold:", indices_exceeding_threshold)
print("Values exceeding threshold:", values_exceeding_threshold)

# Replace values exceeding the threshold with 0
random_array[indices_exceeding_threshold] = 0

# Print the modified array
print("Modified array:", random_array)

Atividade 3
Foi adicionado uma lista para representar as vendas mensais de três empresas ao longo do ano.

Transforme essa lista em Array;
Calcule o valor minimo, maximo e medio da lista;
Calcule a soma de cada mês e adicione uma coluna com esses resultados;
Calcule a média de cada empresa (e da soma) e adicione como linha final;
Remova as agregações;
Separe o array em 4 arrays de trimestres.
Faça as vendas esperadas para o ano seguinte. Espera-se que o primeiro trimestre terá um crescimento de 5%, 15% para o segundo trimestre, queda de 5% para o terceiro trimestre e crescimento de 20% para o último trimestre.
Junte esses arrays em um novo array, mantendo a separação por trimestre.
Desafio: Faça as vendas esperadas através da multiplicação do array de vendas trimestrais pelo array de crescimento. Transforme o array resultante para que ele tenha o mesmo shape do array original.

Espera-se Split, Stack, Concatenate e Delete.

vendas_mensais= [
    [10000, 15000, 20000],  # Janeiro
    [11000, 14000, 22000],  # Fevereiro
    [12000, 16000, 21000],  # Março
    [10500, 15500, 21500],  # Abril
    [11500, 14500, 22500],  # Maio
    [12500, 16500, 20500],  # Junho
    [13000, 17000, 19500],  # Julho
    [13500, 17500, 18500],  # Agosto
    [14000, 18000, 17500],  # Setembro
    [14500, 18500, 16500],  # Outubro
    [15000, 19000, 15500],  # Novembro
    [15500, 19500, 14500]   # Dezembro
]

In [19]:
import numpy as np

vendas_mensais= [
    [10000, 15000, 20000],  # Janeiro
    [11000, 14000, 22000],  # Fevereiro
    [12000, 16000, 21000],  # Março
    [10500, 15500, 21500],  # Abril
    [11500, 14500, 22500],  # Maio
    [12500, 16500, 20500],  # Junho
    [13000, 17000, 19500],  # Julho
    [13500, 17500, 18500],  # Agosto
    [14000, 18000, 17500],  # Setembro
    [14500, 18500, 16500],  # Outubro
    [15000, 19000, 15500],  # Novembro
    [15500, 19500, 14500]   # Dezembro
]
print(vendas_mensais)

# Lista com os arrays de vendas mensais das empresas
vendas_array = np.array(vendas_mensais)
print (vendas_array)

# Calculando valor mínimo
minimo = min(min(mes) for mes in vendas_mensais)
print("Valor mínimo de vendas da lista:", minimo)

# Calculando valor máximo
maximo = max(max(mes) for mes in vendas_mensais)
print("Valor máximo de vendas da lista:", maximo)

# Calculando média
total_vendas = sum(sum(mes) for mes in vendas_mensais)
num_meses = len(vendas_mensais)
media = total_vendas / (num_meses * len(vendas_mensais[0]))
print("Média de vendas da lista:", media)


# Valor mínimo
valor_minimo = np.min(vendas_array)
print("Valor mínimo de vendas do  array:", valor_minimo)

# Valor máximo
valor_maximo = np.max(vendas_array)
print("Valor máximo de vendas do  array:", valor_maximo)

# Média
media_vendas = np.mean(vendas_array)
print("Média de vendas do  array:", media_vendas)



[[10000, 15000, 20000], [11000, 14000, 22000], [12000, 16000, 21000], [10500, 15500, 21500], [11500, 14500, 22500], [12500, 16500, 20500], [13000, 17000, 19500], [13500, 17500, 18500], [14000, 18000, 17500], [14500, 18500, 16500], [15000, 19000, 15500], [15500, 19500, 14500]]
[[10000 15000 20000]
 [11000 14000 22000]
 [12000 16000 21000]
 [10500 15500 21500]
 [11500 14500 22500]
 [12500 16500 20500]
 [13000 17000 19500]
 [13500 17500 18500]
 [14000 18000 17500]
 [14500 18500 16500]
 [15000 19000 15500]
 [15500 19500 14500]]
Valor mínimo de vendas da lista: 10000
Valor máximo de vendas da lista: 22500
Média de vendas da lista: 16208.333333333334
Valor mínimo de vendas do  array: 10000
Valor máximo de vendas do  array: 22500
Média de vendas do  array: 16208.333333333334


In [27]:
# Calcular a média das vendas de cada empresa
soma_por_mes = np.sum(vendas_array, axis=1)

# Adicionar uma coluna com os resultados de soma por mês
matriz_soma_mes = np.column_stack((vendas_array, soma_por_mes))

# Imprimir a matriz com a coluna de soma por mês
print("Matriz de vendas mensais com soma por mês:\n")
print(matriz_soma_mes)

Matriz de vendas mensais com soma por mês:

[[10000 15000 20000 45000]
 [11000 14000 22000 47000]
 [12000 16000 21000 49000]
 [10500 15500 21500 47500]
 [11500 14500 22500 48500]
 [12500 16500 20500 49500]
 [13000 17000 19500 49500]
 [13500 17500 18500 49500]
 [14000 18000 17500 49500]
 [14500 18500 16500 49500]
 [15000 19000 15500 49500]
 [15500 19500 14500 49500]]


In [29]:
# Calcular a média de cada coluna
media_por_coluna = np.mean(matriz_soma_mes, axis=0)
print (media_por_coluna)
# Adicionar uma nova linha com as médias de vendas por mês
matriz_media_empresa_mes = np.vstack((matriz_soma_mes, media_por_coluna))

# Imprimir a matriz com a nova linha de média por coluna
print("Matriz de vendas mensais com média por coluna:")
print(matriz_media_empresa_mes)

[12750. 16750. 19125. 48625.]
Matriz de vendas mensais com média por coluna:
[[10000. 15000. 20000. 45000.]
 [11000. 14000. 22000. 47000.]
 [12000. 16000. 21000. 49000.]
 [10500. 15500. 21500. 47500.]
 [11500. 14500. 22500. 48500.]
 [12500. 16500. 20500. 49500.]
 [13000. 17000. 19500. 49500.]
 [13500. 17500. 18500. 49500.]
 [14000. 18000. 17500. 49500.]
 [14500. 18500. 16500. 49500.]
 [15000. 19000. 15500. 49500.]
 [15500. 19500. 14500. 49500.]
 [12750. 16750. 19125. 48625.]]


In [64]:
nova_matriz = np.delete(matriz_media_empresa_mes, 12, axis=0)

print(nova_matriz)

nova_matriz = np.delete(nova_matriz, 2, axis=1)
print(nova_matriz)

tri = np.split(nova_matriz, 4, axis=0)
print(tri)


print("Trimestre 1:")
print(tri[:1])
print()

print("Trimestre 2:")
print(tri[1:2])
print()

print("Trimestre 3:")
print(tri[2:3])
print()

print("Trimestre 4:")
print(tri[3:])

[[10000. 15000. 20000. 45000.]
 [11000. 14000. 22000. 47000.]
 [12000. 16000. 21000. 49000.]
 [10500. 15500. 21500. 47500.]
 [11500. 14500. 22500. 48500.]
 [12500. 16500. 20500. 49500.]
 [13000. 17000. 19500. 49500.]
 [13500. 17500. 18500. 49500.]
 [14000. 18000. 17500. 49500.]
 [14500. 18500. 16500. 49500.]
 [15000. 19000. 15500. 49500.]
 [15500. 19500. 14500. 49500.]]
[[10000. 15000. 45000.]
 [11000. 14000. 47000.]
 [12000. 16000. 49000.]
 [10500. 15500. 47500.]
 [11500. 14500. 48500.]
 [12500. 16500. 49500.]
 [13000. 17000. 49500.]
 [13500. 17500. 49500.]
 [14000. 18000. 49500.]
 [14500. 18500. 49500.]
 [15000. 19000. 49500.]
 [15500. 19500. 49500.]]
[array([[10000., 15000., 45000.],
       [11000., 14000., 47000.],
       [12000., 16000., 49000.]]), array([[10500., 15500., 47500.],
       [11500., 14500., 48500.],
       [12500., 16500., 49500.]]), array([[13000., 17000., 49500.],
       [13500., 17500., 49500.],
       [14000., 18000., 49500.]]), array([[14500., 18500., 49500.],
 

In [72]:

# Fatores de crescimento ou queda para cada trimestre
fator_trimestre1 = np.array([[1.05, 1.05, 1.05], [1.05, 1.05, 1.05],[1.05, 1.05, 1.05]])  # crescimento de 5%
fator_trimestre2 = np.array([[1.15, 1.15, 1.15], [1.15, 1.15, 1.15],[1.15, 1.15, 1.15]])  # crescimento de 15%
fator_trimestre3 = np.array([[0.95,0.95, 0.95], [0.95, 0.95, 0.95],[0.95, 0.95, 0.95]]) # queda de 5%
fator_trimestre4 = np.array([[1.20,1.20,1.20], [1.20,1.20,1.20],[1.20,1.20,1.20]])   # crescimento de 20%

# Calculando as vendas esperadas para o próximo ano
vendas_esperadas_trimestre1 = tri[:1] * fator_trimestre1
vendas_esperadas_trimestre2 = tri[1:2] * fator_trimestre2
vendas_esperadas_trimestre3 = tri[2:3] * fator_trimestre3
vendas_esperadas_trimestre4 = tri[3:] * fator_trimestre4

# Imprimindo as vendas esperadas para cada trimestre
print("Vendas esperadas para o próximo ano:")
print("Trimestre 1:")
print(vendas_esperadas_trimestre1)
print()
print("Trimestre 2:")
print(vendas_esperadas_trimestre2)
print()
print("Trimestre 3:")
print(vendas_esperadas_trimestre3)
print()
print("Trimestre 4:")
print(vendas_esperadas_trimestre4)

Vendas esperadas para o próximo ano:
Trimestre 1:
[[[10500. 15750. 47250.]
  [11550. 14700. 49350.]
  [12600. 16800. 51450.]]]

Trimestre 2:
[[[12075. 17825. 54625.]
  [13225. 16675. 55775.]
  [14375. 18975. 56925.]]]

Trimestre 3:
[[[12350. 16150. 47025.]
  [12825. 16625. 47025.]
  [13300. 17100. 47025.]]]

Trimestre 4:
[[[17400. 22200. 59400.]
  [18000. 22800. 59400.]
  [18600. 23400. 59400.]]]


In [76]:

# Agrupar os arrays em uma matriz mantendo sua configuração original
matriz_vendas_esperadas = np.stack((vendas_esperadas_trimestre1,
                                          vendas_esperadas_trimestre2,
                                          vendas_esperadas_trimestre3,
                                          vendas_esperadas_trimestre4))

# Imprimir a matriz resultante
print("Matriz de vendas esperadas para o próximo ano por semestre:\n")
print(matriz_vendas_esperadas)
print()

matriz_esperadas = np.concatenate((vendas_esperadas_trimestre1,
                                          vendas_esperadas_trimestre2,
                                          vendas_esperadas_trimestre3,
                                          vendas_esperadas_trimestre4), axis=1)

# Imprimir a matriz resultante
print("Matriz de vendas esperadas para o próximo ano das empresas:\n")
print(matriz_esperadas)


Matriz de vendas esperadas para o próximo ano por semestre:

[[[[10500. 15750. 47250.]
   [11550. 14700. 49350.]
   [12600. 16800. 51450.]]]


 [[[12075. 17825. 54625.]
   [13225. 16675. 55775.]
   [14375. 18975. 56925.]]]


 [[[12350. 16150. 47025.]
   [12825. 16625. 47025.]
   [13300. 17100. 47025.]]]


 [[[17400. 22200. 59400.]
   [18000. 22800. 59400.]
   [18600. 23400. 59400.]]]]

Matriz de vendas esperadas para o próximo ano das empresas:

[[[10500. 15750. 47250.]
  [11550. 14700. 49350.]
  [12600. 16800. 51450.]
  [12075. 17825. 54625.]
  [13225. 16675. 55775.]
  [14375. 18975. 56925.]
  [12350. 16150. 47025.]
  [12825. 16625. 47025.]
  [13300. 17100. 47025.]
  [17400. 22200. 59400.]
  [18000. 22800. 59400.]
  [18600. 23400. 59400.]]]
